---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: demo-ocp
  namespace: book-import
  labels:
    app.kubernetes.io/name: bookimport
spec:
  tower_auth_secret: toweraccess
  job_template_name: sample-job-template
  extra_vars:
    app_name: bookimport
